-- AddCategoryToQuestion
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "category" TEXT DEFAULT 'General';
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AddBioToUser
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;

-- AddFieldsToAIResponse
ALTER TABLE "AIResponse" ADD COLUMN IF NOT EXISTS "detailedExplanation" TEXT;
ALTER TABLE "AIResponse" ADD COLUMN IF NOT EXISTS "processingTime" INTEGER;
ALTER TABLE "AIResponse" ADD COLUMN IF NOT EXISTS "documentsUsed" INTEGER;
